"""Seed the reference instrument catalog.

This seeds *instrument metadata* (symbols, names, exchanges, types, lot and
tick sizes) used by the paper-trading simulation. The values are indicative
reference data for development; authoritative instrument master data will be
synchronised from a broker/exchange feed in a later phase.

Market *prices* are generated by the mock market-data provider and are never
derived from this file.

Usage:
    python -m app.seed                 # seed everything
    python -m app.seed --exchange NSE  # seed only one exchange
"""

import argparse
from dataclasses import dataclass
from datetime import date

from sqlalchemy.orm import Session

from app.core.database import SessionLocal
from app.models.instrument import Instrument
from app.repositories.instruments import InstrumentRepository

# Indicative quarterly expiry used for the F&O catalog rows.
_QUARTERLY_EXPIRY = date(2026, 9, 24)


@dataclass(frozen=True)
class CatalogRow:
    symbol: str
    name: str
    exchange: str
    instrument_type: str
    segment: str
    expiry: date | None
    strike_price: float | None
    option_type: str | None
    lot_size: int
    tick_size: float


def _eq(symbol: str, name: str, exchange: str = "NSE") -> CatalogRow:
    return CatalogRow(symbol, name, exchange, "EQUITY", "EQ", None, None, None, 1, 0.05)


def _fut(symbol: str, name: str, exchange: str, lot_size: int, tick_size: float) -> CatalogRow:
    return CatalogRow(
        symbol, name, exchange, "FUTURE", "FUT", _QUARTERLY_EXPIRY, None, None, lot_size, tick_size
    )


def _opt(
    symbol: str,
    name: str,
    exchange: str,
    strike: float,
    option_type: str,
    lot_size: int,
) -> CatalogRow:
    return CatalogRow(
        symbol,
        name,
        exchange,
        "OPTION",
        "OPT",
        _QUARTERLY_EXPIRY,
        strike,
        option_type,
        lot_size,
        0.05,
    )


NSE_EQUITY = [
    _eq("RELIANCE", "Reliance Industries Ltd"),
    _eq("TCS", "Tata Consultancy Services Ltd"),
    _eq("HDFCBANK", "HDFC Bank Ltd"),
    _eq("INFY", "Infosys Ltd"),
    _eq("ICICIBANK", "ICICI Bank Ltd"),
    _eq("SBIN", "State Bank of India"),
    _eq("BHARTIARTL", "Bharti Airtel Ltd"),
    _eq("ITC", "ITC Ltd"),
    _eq("LT", "Larsen & Toubro Ltd"),
    _eq("HINDUNILVR", "Hindustan Unilever Ltd"),
    _eq("TATAMOTORS", "Tata Motors Ltd"),
    _eq("WIPRO", "Wipro Ltd"),
    _eq("AXISBANK", "Axis Bank Ltd"),
    _eq("KOTAKBANK", "Kotak Mahindra Bank Ltd"),
    _eq("BAJFINANCE", "Bajaj Finance Ltd"),
    _eq("MARUTI", "Maruti Suzuki India Ltd"),
    _eq("SUNPHARMA", "Sun Pharmaceutical Industries Ltd"),
    _eq("TITAN", "Titan Company Ltd"),
    _eq("ULTRACEMCO", "UltraTech Cement Ltd"),
    _eq("NTPC", "NTPC Ltd"),
    _eq("POWERGRID", "Power Grid Corporation of India Ltd"),
    _eq("ONGC", "Oil and Natural Gas Corporation Ltd"),
    _eq("COALINDIA", "Coal India Ltd"),
    _eq("ADANIENT", "Adani Enterprises Ltd"),
    _eq("HCLTECH", "HCL Technologies Ltd"),
    _eq("ASIANPAINT", "Asian Paints Ltd"),
    _eq("DIVISLAB", "Divi's Laboratories Ltd"),
    _eq("TECHM", "Tech Mahindra Ltd"),
    _eq("CIPLA", "Cipla Ltd"),
    _eq("DRREDDY", "Dr. Reddy's Laboratories Ltd"),
]

NSE_FUTURES = [
    _fut("NIFTY", "Nifty 50 Index Future", "NSE", 75, 0.05),
    _fut("BANKNIFTY", "Nifty Bank Index Future", "NSE", 15, 0.05),
    _fut("FINNIFTY", "Nifty Financial Services Index Future", "NSE", 40, 0.05),
    _fut("MIDCPNIFTY", "Nifty Midcap Select Index Future", "NSE", 75, 0.05),
    _fut("RELIANCE", "Reliance Industries Future", "NSE", 500, 0.05),
    _fut("TCS", "Tata Consultancy Services Future", "NSE", 400, 0.05),
    _fut("HDFCBANK", "HDFC Bank Future", "NSE", 1100, 0.05),
    _fut("INFY", "Infosys Future", "NSE", 800, 0.05),
    _fut("ICICIBANK", "ICICI Bank Future", "NSE", 2000, 0.05),
    _fut("SBIN", "State Bank of India Future", "NSE", 1000, 0.05),
]

NSE_OPTIONS = [
    _opt("NIFTY19500CE", "Nifty 19500 Call", "NSE", 19500, "CE", 75),
    _opt("NIFTY19500PE", "Nifty 19500 Put", "NSE", 19500, "PE", 75),
    _opt("NIFTY19600CE", "Nifty 19600 Call", "NSE", 19600, "CE", 75),
    _opt("NIFTY19600PE", "Nifty 19600 Put", "NSE", 19600, "PE", 75),
    _opt("BANKNIFTY44000CE", "Nifty Bank 44000 Call", "NSE", 44000, "CE", 15),
    _opt("BANKNIFTY44000PE", "Nifty Bank 44000 Put", "NSE", 44000, "PE", 15),
    _opt("RELIANCE2400CE", "Reliance 2400 Call", "NSE", 2400, "CE", 500),
    _opt("RELIANCE2400PE", "Reliance 2400 Put", "NSE", 2400, "PE", 500),
    _opt("TCS3000CE", "TCS 3000 Call", "NSE", 3000, "CE", 400),
    _opt("HDFCBANK1500CE", "HDFC Bank 1500 Call", "NSE", 1500, "CE", 1100),
]

BSE_EQUITY = [
    _eq("RELIANCE", "Reliance Industries Ltd", "BSE"),
    _eq("TCS", "Tata Consultancy Services Ltd", "BSE"),
    _eq("INFY", "Infosys Ltd", "BSE"),
    _eq("HDFCBANK", "HDFC Bank Ltd", "BSE"),
    _eq("TATAMOTORS", "Tata Motors Ltd", "BSE"),
    _eq("WIPRO", "Wipro Ltd", "BSE"),
    _eq("BHARTIARTL", "Bharti Airtel Ltd", "BSE"),
    _eq("ICICIBANK", "ICICI Bank Ltd", "BSE"),
]

MCX_FUTURES = [
    _fut("GOLD", "Gold Futures (1 kg)", "MCX", 100, 1.0),
    _fut("SILVER", "Silver Futures (30 kg)", "MCX", 30, 1.0),
    _fut("CRUDEOIL", "Crude Oil Futures", "MCX", 100, 1.0),
    _fut("NATURALGAS", "Natural Gas Futures", "MCX", 1250, 0.1),
    _fut("COPPER", "Copper Futures", "MCX", 2500, 0.05),
]

CATALOG: list[CatalogRow] = (
    NSE_EQUITY + NSE_FUTURES + NSE_OPTIONS + BSE_EQUITY + MCX_FUTURES
)


def seed_instruments(
    db: Session, exchanges: set[str] | None = None
) -> int:
    repo = InstrumentRepository(db)
    count = 0
    for row in CATALOG:
        if exchanges and row.exchange not in exchanges:
            continue
        existing = repo.get_by_natural_key(
            row.exchange,
            row.symbol,
            row.instrument_type,
            row.expiry,
            row.strike_price,
            row.option_type,
        )
        values = {
            "name": row.name,
            "instrument_type": row.instrument_type,
            "segment": row.segment,
            "expiry": row.expiry,
            "strike_price": row.strike_price,
            "option_type": row.option_type,
            "lot_size": row.lot_size,
            "tick_size": row.tick_size,
            "is_active": True,
        }
        if existing is None:
            db.add(
                Instrument(
                    symbol=row.symbol,
                    exchange=row.exchange,
                    **values,
                )
            )
        else:
            for key, value in values.items():
                setattr(existing, key, value)
        count += 1
    db.commit()
    return count


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--exchange",
        action="append",
        choices=["NSE", "BSE", "MCX"],
        help="Seed only this exchange (repeatable).",
    )
    args = parser.parse_args()
    with SessionLocal() as db:
        count = seed_instruments(db, exchanges=set(args.exchange or []))
    print(f"Seeded {count} instruments.")


if __name__ == "__main__":
    main()
